version: "2.1"
services:
  bundesliga:
    image: lukasdotcom/fantasy-manager:1 # Change 1 to latest if you want the last stable release. Major versions may have trouble between upgrades read the release before any update.
    container_name: bundesliga
    # links:
    #   - db
    environment:
      - NEXTAUTH_URL=http://localhost # The url of the server
      - SQLITE=/mnt/bundesliga.db
      - MIN_UPDATE_TIME=120
      - MIN_UPDATE_TIME_TRANSFER=3600
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET} # run openssl rand -base64 32 and plug the result into this
      - ADMIN=1
    ports:
      - 80:3000
    restart: always
    volumes:
      - bundesliga:/mnt
    # Uncomment the following if you want the downloaded pictures to persist between updates. Leave this commented if you set DOWNLOAD_PICTURE to no. If you set DOWNLOAD_PICTURE to yes you should uncomment it.
    #  - pictures:/app/players
volumes:
  bundesliga:
  # bundesliga:
  #   external: true
  #pictures:
  #  external: true
