name: OWASP Dependency-Check for JavaScript

on:
  push:
    branches:
      - main  # Change this to your target branch
  pull_request:
    branches:
      - main  # Change this to your target branch

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Run OWASP Dependency-Check
        uses: dependency-check-action/dependency-check-action@v2
        with:
          format: 'ALL'  # Options: ALL, XML, JSON, HTML
          outputDirectory: 'dependency-check-report'
          failOnCVSS: 7  # Fail the build if any vulnerabilities with CVSS score >= 7 are found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
